name: art_catalog_app
description: "Flutter app that allows users to navigate the catalog of artworks exposed by the Art Institute of Chicago"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #BloC library
  flutter_bloc: ^8.1.5
  #Service Locator
  get_it: ^7.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  http: ^1.2.1
  auto_route: ^8.1.1
  intl: ^0.19.0
  equatable: ^2.0.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  shimmer: ^3.0.0
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  bloc_test: ^9.1.7
  freezed: ^2.5.2
  build_runner: ^2.4.9
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  auto_route_generator: ^8.0.0
  isar_generator: ^3.1.0+1

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

flutter:

  uses-material-design: true

  assets:
    - lib/assets/


